version: '3.8'

services:
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: docker/frontend.dockerfile
  #   volumes:
  #     - config_frontend:/app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #   depends_on:
  #     - backend
  #   networks:
  #     - bidi_network
  #   restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    volumes:
      - storage_data:/app/storage
      - config_backend:/app
    ports:
      - "8000:8000"
    networks:
      - bidi_network
    restart: unless-stopped

  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/ssl:/etc/nginx/ssl
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - bidi_network
  #   restart: unless-stopped

volumes:
  storage_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/backend/storage
  config_frontend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/frontend
  config_backend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/backend

networks:
  bidi_network:
    driver: bridge 