version: '3.8'

services:
  backend:
    image: ahmetkoprulu/bidi-menu-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./development.env
    networks:
      - bidi_network
      - external_postgres_network
    restart: unless-stopped
    volumes:
      - ./migrations:/app/migrations
      - ./storage:/app/storage

volumes:
  bidi_storage:

networks:
  bidi_network:
    driver: bridge 
  external_postgres_network:
    external:
      name: postgres-network 